[package]
name = "zkane"
version = "0.1.0"
edition = "2021"
description = "Privacy pool for alkanes assets using zero-knowledge proofs"
license = "MIT"
repository = "https://github.com/zkane-project/zkane"

[workspace]
members = [
    "crates/zkane-common",
    "crates/zkane-crypto", 
    "crates/zkane-core",
    "crates/zkane-wasm",
    "alkanes/zkane",
    "alkanes/zkane-factory",
]

[dependencies]
# Core ZKane crates
zkane-common = { path = "crates/zkane-common" }
zkane-crypto = { path = "crates/zkane-crypto" }
zkane-core = { path = "crates/zkane-core" }
zkane-wasm = { path = "crates/zkane-wasm", optional = true }

# Alkanes framework
alkanes = { git = "https://github.com/sandshrewmetaprotocols/alkanes", branch = "main" }
alkanes-support = { git = "https://github.com/sandshrewmetaprotocols/alkanes", branch = "main" }

# Protorune dependencies
protorune = { git = "https://github.com/sandshrewmetaprotocols/protorune", branch = "main" }
protorune-support = { git = "https://github.com/sandshrewmetaprotocols/protorune", branch = "main" }

# Metashrew dependencies
metashrew-core = { git = "https://github.com/sandshrewmetaprotocols/metashrew", branch = "main" }
metashrew-support = { git = "https://github.com/sandshrewmetaprotocols/metashrew", branch = "main" }

# Bitcoin and cryptography
bitcoin = "0.32"
sha2 = "0.10"
hex = "0.4"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Async and utilities
tokio = { version = "1.0", features = ["full"], optional = true }

# Testing dependencies
[dev-dependencies]
wasm-bindgen-test = "0.3"

[features]
default = ["std"]
std = []
wasm = ["zkane-wasm"]
async = ["tokio"]

# WASM-specific configuration
[lib]
crate-type = ["cdylib", "rlib"]

# Optimization for WASM builds
[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
opt-level = 0
debug = true
overflow-checks = true

# WASM-pack configuration
[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Os", "--enable-mutable-globals"]

[package.metadata.wasm-pack.profile.dev]
wasm-opt = false