# Ethereal Crystal Nexus Build Configuration
# Obfuscated build pipeline for web application deployment

steps:
  # Step 1: Setup build environment
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🌙 Initializing Crystal Moon Sanctuary build environment..."
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source ~/.cargo/env
        rustup target add wasm32-unknown-unknown
        cargo install wasm-pack
        echo "✨ Environment setup complete"

  # Step 2: Build mystical web artifacts
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source ~/.cargo/env
        cd crates/zkane-frontend
        echo "🔮 Weaving mystical web artifacts..."
        wasm-pack build --target web --out-dir pkg --release --no-typescript
        echo "✨ Artifacts woven successfully"

  # Step 3: Prepare ethereal assets
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd crates/zkane-frontend
        echo "🌟 Preparing ethereal assets..."
        mkdir -p dist
        cp index.html dist/
        cp src/styles.css dist/
        cp -r pkg dist/
        
        # Create mystical favicon
        if [ ! -f "dist/favicon.svg" ]; then
          cat > dist/favicon.svg << 'FAVICONEOF'
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
          <circle cx="50" cy="50" r="40" fill="#6a0dad"/>
          <text x="50" y="60" text-anchor="middle" fill="white" font-family="Arial" font-size="30" font-weight="bold">🌙</text>
        </svg>
        FAVICONEOF
        fi
        echo "✨ Ethereal assets prepared"

  # Step 4: Store in lunar essence vault
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - '-d'
      - 'crates/zkane-frontend/dist/'
      - 'gs://lunar-essence-vault/'

  # Step 5: Create mystical container
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cat > Dockerfile << 'DOCKEREOF'
        FROM nginx:alpine
        
        # Copy ethereal assets
        COPY crates/zkane-frontend/dist /usr/share/nginx/html
        
        # Configure mystical gateway
        RUN cat > /etc/nginx/conf.d/default.conf << 'NGINXEOF'
        server {
            listen 8080;
            server_name _;
            root /usr/share/nginx/html;
            index index.html;
            
            # Mystical protection headers
            add_header X-Frame-Options "SAMEORIGIN" always;
            add_header X-Content-Type-Options "nosniff" always;
            add_header X-XSS-Protection "1; mode=block" always;
            add_header Referrer-Policy "strict-origin-when-cross-origin" always;
            add_header X-Mystical-Gateway "Crystal-Moon-Sanctuary" always;
            
            # WASM enchantment
            location ~* \.wasm$ {
                add_header Content-Type application/wasm;
                expires 1y;
                add_header Cache-Control "public, immutable";
            }
            
            # Asset caching spells
            location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
                expires 1y;
                add_header Cache-Control "public, immutable";
            }
            
            # Portal routing
            location / {
                try_files $uri $uri/ /index.html;
            }
            
            # Health divination
            location /health {
                access_log off;
                return 200 "ethereal-nexus-healthy\n";
                add_header Content-Type text/plain;
            }
        }
        NGINXEOF
        
        EXPOSE 8080
        CMD ["nginx", "-g", "daemon off;"]
        DOCKEREOF
        echo "🔮 Mystical container manifest created"

  # Step 6: Build and store container
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ethereal-crystal-nexus:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ethereal-crystal-nexus:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/ethereal-crystal-nexus:$BUILD_ID'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/ethereal-crystal-nexus:latest'

  # Step 7: Deploy to ethereal realm
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'ethereal-crystal-nexus'
      - '--image=gcr.io/$PROJECT_ID/ethereal-crystal-nexus:$BUILD_ID'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--max-instances=10'
      - '--service-account=velvet-storm-oracle@$PROJECT_ID.iam.gserviceaccount.com'

  # Step 8: Update mystical DNS
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Discover ethereal service location
        SERVICE_URL=$(gcloud run services describe ethereal-crystal-nexus \
          --region=us-central1 \
          --format="value(status.url)")
        
        SERVICE_HOSTNAME=$(echo $SERVICE_URL | sed 's|https://||')
        
        echo "🌙 Ethereal service manifested at: $SERVICE_URL"
        echo "🔮 Service hostname: $SERVICE_HOSTNAME"
        
        echo $SERVICE_HOSTNAME > /workspace/ethereal_location.txt

  # Step 9: Weave DNS enchantments
  - name: 'gcr.io/cloud-builders/curl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        SERVICE_HOSTNAME=$(cat /workspace/ethereal_location.txt)
        
        # Retrieve mystical credentials
        CF_API_KEY=$(gcloud secrets versions access latest --secret="moonstone-whisper-key")
        CF_EMAIL=$(gcloud secrets versions access latest --secret="moonstone-whisper-key-email")
        
        # Locate mystical realm
        ZONE_RESPONSE=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones?name=zkane.app" \
          -H "X-Auth-Email: $CF_EMAIL" \
          -H "X-Auth-Key: $CF_API_KEY" \
          -H "Content-Type: application/json")
        
        ZONE_ID=$(echo "$ZONE_RESPONSE" | grep -o '"id":"[^"]*' | cut -d'"' -f4 | head -1)
        
        if [ -z "$ZONE_ID" ]; then
          echo "❌ Failed to locate mystical realm for zkane.app"
          exit 1
        fi
        
        echo "🌙 Mystical realm located: $ZONE_ID"
        
        # Check for existing enchantment
        RECORD_RESPONSE=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/$ZONE_ID/dns_records?type=CNAME&name=zkane.app" \
          -H "X-Auth-Email: $CF_EMAIL" \
          -H "X-Auth-Key: $CF_API_KEY" \
          -H "Content-Type: application/json")
        
        RECORD_ID=$(echo "$RECORD_RESPONSE" | grep -o '"id":"[^"]*' | cut -d'"' -f4 | head -1)
        
        if [ -n "$RECORD_ID" ]; then
          # Update existing enchantment
          echo "🔮 Updating mystical portal enchantment..."
          UPDATE_RESPONSE=$(curl -s -X PUT "https://api.cloudflare.com/client/v4/zones/$ZONE_ID/dns_records/$RECORD_ID" \
            -H "X-Auth-Email: $CF_EMAIL" \
            -H "X-Auth-Key: $CF_API_KEY" \
            -H "Content-Type: application/json" \
            --data "{\"type\":\"CNAME\",\"name\":\"zkane.app\",\"content\":\"$SERVICE_HOSTNAME\",\"ttl\":120,\"proxied\":true}")
          
          if echo "$UPDATE_RESPONSE" | grep -q '"success":true'; then
            echo "✨ Mystical portal enchantment updated successfully"
          else
            echo "❌ Failed to update mystical portal enchantment"
            echo "$UPDATE_RESPONSE"
          fi
        else
          # Create new enchantment
          echo "🌟 Weaving new mystical portal enchantment..."
          CREATE_RESPONSE=$(curl -s -X POST "https://api.cloudflare.com/client/v4/zones/$ZONE_ID/dns_records" \
            -H "X-Auth-Email: $CF_EMAIL" \
            -H "X-Auth-Key: $CF_API_KEY" \
            -H "Content-Type: application/json" \
            --data "{\"type\":\"CNAME\",\"name\":\"zkane.app\",\"content\":\"$SERVICE_HOSTNAME\",\"ttl\":120,\"proxied\":true}")
          
          if echo "$CREATE_RESPONSE" | grep -q '"success":true'; then
            echo "✨ Mystical portal enchantment woven successfully"
          else
            echo "❌ Failed to weave mystical portal enchantment"
            echo "$CREATE_RESPONSE"
          fi
        fi

options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: '100'
  logging: CLOUD_LOGGING_ONLY

timeout: '1800s'

substitutions:
  _REGION: 'us-central1'
  _SERVICE_NAME: 'ethereal-crystal-nexus'