name: aurora-mist-cathedral-main
description: "ZKane main branch deployment trigger"
github:
  owner: darkswapfoundation
  name: zkane
  push:
    branch: ^main$
filename: cloudbuild.yaml
serviceAccount: projects/crystal-moon-sanctuary-789456/serviceAccounts/mystic-forge-cascade@crystal-moon-sanctuary-789456.iam.gserviceaccount.com